version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  code-quality-check-and-test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install uv && uv sync
      - run:
          name: code quality check
          command: |
            uv tool run black . --check --line-length 120
            uv tool run ruff check --line-length 120 .
            uv tool run mypy . --ignore-missing-imports
            uv tool run isort . --check
      - run:
          name: run tests
          command:
            uv run pytest

  pypi-publish:
    docker:
      - image: cimg/python:3.12.5
    steps:
      - checkout
      - run:
          command: |
            pip install twine uv 
            uvx --from build pyproject-build --installer uv 
            uvx twine upload --repository-url $JFROG_PUBLISH_URL dist/* -u $JFROG_USERNAME -p $JFROG_TOKEN

workflows:
  publish-package-to-code-artifact:
    jobs:
      - code-quality-check-and-test:
          context:
            - PackageAuthentication
            - CaptionPartners
      - pypi-publish:
          context:
            - PackageAuthentication
          requires:
            - code-quality-check-and-test
          filters:
            branches:
              only: main
